
name: PR Production
on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      API_DOMAIN: https://1vh9c7kivh.execute-api.ap-southeast-1.amazonaws.com/production/
      CDN_DOMAIN: https://d2vjy6bhj0z1t0.cloudfront.net/uploads/
      PLATFORM: android
      PREFIX: kkp
      ENVIRONMENT: PROD
  
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: npm
      - run: npm config set registry http://registry.npmjs.org/
      - run: npm install --production=true
      - run: echo "APP_ENV_PROJECT=Leni2022" >> .env
      - run: echo "APP_ENV_PLATFORM=$PLATFORM" >> .env
      - run: echo "APP_ENV_PREFIX=$PREFIX" >> .env
      - run: echo "APP_ENV_PUBLIC_PATH=" >> .env
      - run: echo "APP_ENV_BUILD_NO=1.7.${{ github.run_number }}" >> .env
      - run: echo "APP_ENV_COOKIE_TIME_LIMIT=14" >> .env
      - run: echo "APP_ENV_API_DOMAIN=$API_DOMAIN" >> .env
      - run: echo "APP_ENV_CDN_DOMAIN=$CDN_DOMAIN" >> .env
      - run: echo "APP_ENV_ENVIRONMENT=$ENVIRONMENT" >> .env
      - run: echo "APP_ENV_STAGE=$CI_COMMIT_REF_NAME" >> .env
      - run: cat .env
      - run: npm install
      # - run: npm run test

